# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/clion/164/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /snap/clion/164/bin/cmake/linux/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/vasileios/Desktop/Exercise-4

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/vasileios/Desktop/Exercise-4

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/clion/164/bin/cmake/linux/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/snap/clion/164/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vasileios/Desktop/Exercise-4/CMakeFiles /home/vasileios/Desktop/Exercise-4//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/vasileios/Desktop/Exercise-4/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named multithreaded

# Build rule for target.
multithreaded: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 multithreaded
.PHONY : multithreaded

# fast build rule for target.
multithreaded/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/build
.PHONY : multithreaded/fast

#=============================================================================
# Target rules for targets named seq

# Build rule for target.
seq: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 seq
.PHONY : seq

# fast build rule for target.
seq/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/build
.PHONY : seq/fast

bmm_blocking.o: bmm_blocking.cpp.o
.PHONY : bmm_blocking.o

# target to build an object file
bmm_blocking.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/bmm_blocking.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/bmm_blocking.cpp.o
.PHONY : bmm_blocking.cpp.o

bmm_blocking.i: bmm_blocking.cpp.i
.PHONY : bmm_blocking.i

# target to preprocess a source file
bmm_blocking.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/bmm_blocking.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/bmm_blocking.cpp.i
.PHONY : bmm_blocking.cpp.i

bmm_blocking.s: bmm_blocking.cpp.s
.PHONY : bmm_blocking.s

# target to generate assembly for a file
bmm_blocking.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/bmm_blocking.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/bmm_blocking.cpp.s
.PHONY : bmm_blocking.cpp.s

bmm_multithread.o: bmm_multithread.cpp.o
.PHONY : bmm_multithread.o

# target to build an object file
bmm_multithread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/bmm_multithread.cpp.o
.PHONY : bmm_multithread.cpp.o

bmm_multithread.i: bmm_multithread.cpp.i
.PHONY : bmm_multithread.i

# target to preprocess a source file
bmm_multithread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/bmm_multithread.cpp.i
.PHONY : bmm_multithread.cpp.i

bmm_multithread.s: bmm_multithread.cpp.s
.PHONY : bmm_multithread.s

# target to generate assembly for a file
bmm_multithread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/bmm_multithread.cpp.s
.PHONY : bmm_multithread.cpp.s

headers/file_io.o: headers/file_io.cpp.o
.PHONY : headers/file_io.o

# target to build an object file
headers/file_io.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/headers/file_io.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/headers/file_io.cpp.o
.PHONY : headers/file_io.cpp.o

headers/file_io.i: headers/file_io.cpp.i
.PHONY : headers/file_io.i

# target to preprocess a source file
headers/file_io.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/headers/file_io.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/headers/file_io.cpp.i
.PHONY : headers/file_io.cpp.i

headers/file_io.s: headers/file_io.cpp.s
.PHONY : headers/file_io.s

# target to generate assembly for a file
headers/file_io.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/headers/file_io.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/headers/file_io.cpp.s
.PHONY : headers/file_io.cpp.s

headers/mmio.o: headers/mmio.cpp.o
.PHONY : headers/mmio.o

# target to build an object file
headers/mmio.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/headers/mmio.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/headers/mmio.cpp.o
.PHONY : headers/mmio.cpp.o

headers/mmio.i: headers/mmio.cpp.i
.PHONY : headers/mmio.i

# target to preprocess a source file
headers/mmio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/headers/mmio.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/headers/mmio.cpp.i
.PHONY : headers/mmio.cpp.i

headers/mmio.s: headers/mmio.cpp.s
.PHONY : headers/mmio.s

# target to generate assembly for a file
headers/mmio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/headers/mmio.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/headers/mmio.cpp.s
.PHONY : headers/mmio.cpp.s

headers/my_time.o: headers/my_time.cpp.o
.PHONY : headers/my_time.o

# target to build an object file
headers/my_time.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/headers/my_time.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/headers/my_time.cpp.o
.PHONY : headers/my_time.cpp.o

headers/my_time.i: headers/my_time.cpp.i
.PHONY : headers/my_time.i

# target to preprocess a source file
headers/my_time.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/headers/my_time.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/headers/my_time.cpp.i
.PHONY : headers/my_time.cpp.i

headers/my_time.s: headers/my_time.cpp.s
.PHONY : headers/my_time.s

# target to generate assembly for a file
headers/my_time.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/headers/my_time.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/headers/my_time.cpp.s
.PHONY : headers/my_time.cpp.s

omp.o: omp.cpp.o
.PHONY : omp.o

# target to build an object file
omp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/omp.cpp.o
.PHONY : omp.cpp.o

omp.i: omp.cpp.i
.PHONY : omp.i

# target to preprocess a source file
omp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/omp.cpp.i
.PHONY : omp.cpp.i

omp.s: omp.cpp.s
.PHONY : omp.s

# target to generate assembly for a file
omp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/omp.cpp.s
.PHONY : omp.cpp.s

sequential1.o: sequential1.cpp.o
.PHONY : sequential1.o

# target to build an object file
sequential1.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/sequential1.cpp.o
.PHONY : sequential1.cpp.o

sequential1.i: sequential1.cpp.i
.PHONY : sequential1.i

# target to preprocess a source file
sequential1.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/sequential1.cpp.i
.PHONY : sequential1.cpp.i

sequential1.s: sequential1.cpp.s
.PHONY : sequential1.s

# target to generate assembly for a file
sequential1.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/sequential1.cpp.s
.PHONY : sequential1.cpp.s

sparse/matrix.o: sparse/matrix.cpp.o
.PHONY : sparse/matrix.o

# target to build an object file
sparse/matrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/sparse/matrix.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/sparse/matrix.cpp.o
.PHONY : sparse/matrix.cpp.o

sparse/matrix.i: sparse/matrix.cpp.i
.PHONY : sparse/matrix.i

# target to preprocess a source file
sparse/matrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/sparse/matrix.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/sparse/matrix.cpp.i
.PHONY : sparse/matrix.cpp.i

sparse/matrix.s: sparse/matrix.cpp.s
.PHONY : sparse/matrix.s

# target to generate assembly for a file
sparse/matrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/sparse/matrix.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/sparse/matrix.cpp.s
.PHONY : sparse/matrix.cpp.s

sparse/sparse.o: sparse/sparse.cpp.o
.PHONY : sparse/sparse.o

# target to build an object file
sparse/sparse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/sparse/sparse.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/sparse/sparse.cpp.o
.PHONY : sparse/sparse.cpp.o

sparse/sparse.i: sparse/sparse.cpp.i
.PHONY : sparse/sparse.i

# target to preprocess a source file
sparse/sparse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/sparse/sparse.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/sparse/sparse.cpp.i
.PHONY : sparse/sparse.cpp.i

sparse/sparse.s: sparse/sparse.cpp.s
.PHONY : sparse/sparse.s

# target to generate assembly for a file
sparse/sparse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/multithreaded.dir/build.make CMakeFiles/multithreaded.dir/sparse/sparse.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/seq.dir/build.make CMakeFiles/seq.dir/sparse/sparse.cpp.s
.PHONY : sparse/sparse.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... multithreaded"
	@echo "... seq"
	@echo "... bmm_blocking.o"
	@echo "... bmm_blocking.i"
	@echo "... bmm_blocking.s"
	@echo "... bmm_multithread.o"
	@echo "... bmm_multithread.i"
	@echo "... bmm_multithread.s"
	@echo "... headers/file_io.o"
	@echo "... headers/file_io.i"
	@echo "... headers/file_io.s"
	@echo "... headers/mmio.o"
	@echo "... headers/mmio.i"
	@echo "... headers/mmio.s"
	@echo "... headers/my_time.o"
	@echo "... headers/my_time.i"
	@echo "... headers/my_time.s"
	@echo "... omp.o"
	@echo "... omp.i"
	@echo "... omp.s"
	@echo "... sequential1.o"
	@echo "... sequential1.i"
	@echo "... sequential1.s"
	@echo "... sparse/matrix.o"
	@echo "... sparse/matrix.i"
	@echo "... sparse/matrix.s"
	@echo "... sparse/sparse.o"
	@echo "... sparse/sparse.i"
	@echo "... sparse/sparse.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

